### ISSUE TITLE
[Suggestion] Fisher Machine

### ISSUE THREAD

**Issue by ImAK9** [TeamRedDragon/RedDragon-Marvelous-Machines#1]
As Tech Reborn dosen't have a Fisher, such a machine would be neat. Thanks for coming to my Ted Talk!

**Comment by SophiaAska** [comment]
Thank you for your suggestion it's a nice request. While it absolutely fits to the vision of Marvelous Machines, we need to think about a balanced game design implementation of a fisher machine.
