### ISSUE TITLE
It would be great to see 1.18.2 update!

### ISSUE THREAD

**Issue by vadim-a-yegorov** [TeamRedDragon/RedDragon-Marvelous-Machines#3]
Hi @SophiaAska @josilo @Jilocasin, are  you planning any update? Project seems pretty abandoned right now, but I would be happy to see 1.18.2 version someday

**Comment by Jilocasin** [comment]
Hey there! Thank you so much for the interest.

This project started when we were casually playing Minecraft in a group of friends. Sadly, as we stopped playing eventually, so did this project come to a stop and eventually become abandonned. I'm sorry to disappoint!

While we certainly don't rule out continuing this project at some point, given enough spare time and energy, for the time being there will not be an update.

**Comment by vadim-a-yegorov** [comment]
Hi @josilo , could you please contact me
